INSERT INTO [dbo].[Productos]
([Nombre], [Marca], [Categoria], [Precio], [Descripcion], [NombreArchivoImagen], [CreadoEn])
VALUES
-- Productos iniciales de la imagen de referencia
('Laptop Pavilion 15', 'HP', 'Computadoras', 699.99, 'Laptop HP Pavilion de 15.6", Intel Core i5, 8GB RAM, 512GB SSD', 'hp_pavilion15.jpg', GETDATE()),
('Laptop IdeaPad 3', 'Lenovo', 'Computadoras', 679.99, 'Lenovo IdeaPad 3, 15", Ryzen 5, 8GB RAM, 256GB SSD', 'lenovo_ideapad3.jpg', GETDATE()),
('Laptop Aspire 5', 'Acer', 'Computadoras', 599.99, 'Acer Aspire 5, 15.6", Intel Core i3, 4GB RAM, 128GB SSD', 'acer_aspire5.jpg', GETDATE()),
('Laptop MacBook Air', 'Apple', 'Computadoras', 1199.99, 'Apple MacBook Air con pantalla Retina, 8GB RAM, 256GB SSD', 'macbook_air.jpg', GETDATE()),
('Mouse Gaming RGB', 'Logitech', 'Accesorios', 49.99, 'Mouse para gaming RGB Logitech G502', 'logitech_g502.jpg', GETDATE()),
('Teclado Mecánico K95', 'Corsair', 'Accesorios', 199.99, 'Teclado mecánico RGB Corsair K95', 'corsair_k95.jpg', GETDATE()),
('Alfombrilla Control Pad', 'SteelSeries', 'Accesorios', 24.99, 'Alfombrilla SteelSeries QcK para gamers', 'steelseries_qck.jpg', GETDATE()),
('Laptop Chromebook C202', 'Asus', 'Computadoras', 229.99, 'Laptop Asus Chromebook C202 para uso escolar', 'asus_chromebook_c202.jpg', GETDATE()),
('Monitor Curvo 27"', 'Samsung', 'Periféricos', 279.99, 'Monitor curvo Samsung LC27F398FWNXZA', 'samsung_curvo_27.jpg', GETDATE()),
('Teclado Ergonomico K350', 'Logitech', 'Accesorios', 79.99, 'Teclado ergonómico inalámbrico Logitech K350', 'logitech_k350.jpg', GETDATE()),
('Monitor 24" Full HD', 'AOC', 'Periféricos', 179.99, 'Monitor AOC 24B1H de 24" Full HD', 'aoc_24b1h.jpg', GETDATE()),
('Router WiFi 6 AX3000', 'TP-Link', 'Periféricos', 69.99, 'Router inalámbrico TP-Link Archer AX50 AX3000', 'tplink_ax50.jpg', GETDATE()),
('Audífonos Gaming', 'HyperX', 'Accesorios', 99.99, 'Audífonos para gaming HyperX Cloud II', 'hyperx_cloud_ii.jpg', GETDATE()),
('Soporte para laptop ajustable', 'Neewer', 'Accesorios', 49.99, 'Soporte ajustable para laptop de aluminio Neewer', 'neewer_laptop_stand.jpg', GETDATE()),
('Impresora Multifuncional', 'Canon', 'Periféricos', 129.99, 'Impresora multifuncional Canon PIXMA MG3620', 'canon_pixma_mg3620.jpg', GETDATE()),
('Audífonos Bluetooth', 'Sony', 'Accesorios', 79.99, 'Audífonos Bluetooth Sony WH-CH510', 'sony_wh_ch510.jpg', GETDATE()),
('Laptop Galaxy Book S', 'Samsung', 'Computadoras', 999.99, 'Samsung Galaxy Book S, 13.3", Intel Core i5, 8GB RAM, 256GB SSD', 'samsung_galaxy_book_s.jpg', GETDATE()),
('Teclado Gaming K70', 'Corsair', 'Accesorios', 149.99, 'Teclado mecánico para gaming Corsair K70 RGB', 'corsair_k70.jpg', GETDATE()),
('Monitor 27" 4K', 'LG', 'Periféricos', 399.99, 'Monitor LG 27" 4K Ultra HD', 'lg_27_4k.jpg', GETDATE()),
-- Productos adicionales - Computadoras
('Laptop Pro 15', 'Dell', 'Computadoras', 899.99, 'Laptop Dell Pro 15 con pantalla táctil, Intel Core i7, 16GB RAM, 512GB SSD', 'dell_pro15.jpg', GETDATE()),
('Laptop ZenBook 13', 'Asus', 'Computadoras', 799.99, 'Ultrabook Asus ZenBook 13, Intel Core i5, 8GB RAM, 256GB SSD', 'asus_zenbook13.jpg', GETDATE()),
('Laptop Inspiron 14', 'Dell', 'Computadoras', 749.99, 'Dell Inspiron 14, Intel Core i5, 8GB RAM, 256GB SSD', 'dell_inspiron14.jpg', GETDATE()),
('Laptop Swift 3', 'Acer', 'Computadoras', 649.99, 'Acer Swift 3, AMD Ryzen 7, 8GB RAM, 256GB SSD', 'acer_swift3.jpg', GETDATE()),
('Laptop Vostro 15', 'Dell', 'Computadoras', 699.99, 'Dell Vostro 15, Intel Core i5, 8GB RAM, 512GB SSD', 'dell_vostro15.jpg', GETDATE()),
('Laptop ProBook 450', 'HP', 'Computadoras', 849.99, 'HP ProBook 450, Intel Core i7, 16GB RAM, 512GB SSD', 'hp_probook450.jpg', GETDATE()),
('Laptop ThinkPad E15', 'Lenovo', 'Computadoras', 799.99, 'Lenovo ThinkPad E15, Intel Core i5, 8GB RAM, 256GB SSD', 'lenovo_thinkpad_e15.jpg', GETDATE()),
('Laptop XPS 13', 'Dell', 'Computadoras', 1199.99, 'Dell XPS 13, pantalla InfinityEdge, Intel Core i7, 16GB RAM, 512GB SSD', 'dell_xps13.jpg', GETDATE()),
('Laptop MateBook 14', 'Huawei', 'Computadoras', 899.99, 'Huawei MateBook 14, AMD Ryzen 5, 8GB RAM, 512GB SSD', 'huawei_matebook14.jpg', GETDATE()),
('Laptop Spectre x360', 'HP', 'Computadoras', 1399.99, 'HP Spectre x360 convertible, Intel Core i7, 16GB RAM, 1TB SSD', 'hp_spectrex360.jpg', GETDATE()),
('Laptop Envy 17', 'HP', 'Computadoras', 1099.99, 'HP Envy 17, Intel Core i7, 16GB RAM, 512GB SSD, pantalla 17"', 'hp_envy17.jpg', GETDATE()),
-- Productos adicionales - Accesorios
('Mouse Inalámbrico X100', 'Logitech', 'Accesorios', 39.99, 'Mouse inalámbrico Logitech X100, sensor óptico de alta precisión', 'logitech_x100.jpg', GETDATE()),
('Teclado Slim', 'Microsoft', 'Accesorios', 59.99, 'Teclado delgado Microsoft, diseño ergonómico y silencioso', 'microsoft_slim.jpg', GETDATE()),
('Auriculares Inalámbricos AirBeat', 'JBL', 'Accesorios', 89.99, 'Auriculares JBL AirBeat con cancelación de ruido', 'jbl_airbeat.jpg', GETDATE()),
('Mouse Gamer Pro', 'Razer', 'Accesorios', 59.99, 'Mouse gamer Razer Pro con iluminación RGB', 'razer_pro.jpg', GETDATE()),
('Teclado Mecánico Compacto', 'HyperX', 'Accesorios', 129.99, 'Teclado mecánico compacto HyperX, ideal para gaming y trabajo', 'hyperx_compact.jpg', GETDATE()),
('Soporte Ergonómico para Monitor', '3M', 'Accesorios', 49.99, 'Soporte ergonómico para monitor de 3M, ajustable y resistente', '3m_monitor_stand.jpg', GETDATE()),
('Base Enfriadora para Laptop', 'Cooler Master', 'Accesorios', 34.99, 'Base enfriadora para laptop Cooler Master, ventiladores integrados', 'cooler_master_base.jpg', GETDATE()),
('Hub USB 3.0', 'Anker', 'Accesorios', 29.99, 'Hub USB 3.0 Anker con 4 puertos y carga rápida', 'anker_hub.jpg', GETDATE()),
('Disco Duro Externo 1TB', 'Seagate', 'Accesorios', 59.99, 'Disco duro externo Seagate de 1TB, USB 3.0', 'seagate_1tb.jpg', GETDATE()),
('Memoria USB 64GB', 'SanDisk', 'Accesorios', 19.99, 'Memoria USB 64GB SanDisk, alta velocidad de transferencia', 'sandisk_64gb.jpg', GETDATE()),
('Cargador Inalámbrico', 'Belkin', 'Accesorios', 49.99, 'Cargador inalámbrico Belkin compatible con múltiples dispositivos', 'belkin_wireless.jpg', GETDATE()),
('Funda Protectora para Laptop', 'CaseLogic', 'Accesorios', 39.99, 'Funda protectora para laptop CaseLogic, resistente y ligera', 'caselogic_laptop.jpg', GETDATE()),
('Batería Externa 20000mAh', 'Anker', 'Accesorios', 59.99, 'Batería externa Anker de 20000mAh para recarga móvil', 'anker_bateria.jpg', GETDATE()),
('Kit de Limpieza para Pantallas', 'OXO', 'Accesorios', 14.99, 'Kit de limpieza OXO para pantallas y dispositivos', 'oxo_limpieza.jpg', GETDATE()),
('Cable HDMI 2.0', 'AmazonBasics', 'Accesorios', 12.99, 'Cable HDMI 2.0 AmazonBasics de alta velocidad', 'amazon_hdmi.jpg', GETDATE()),
('Adaptador USB-C a Ethernet', 'UGREEN', 'Accesorios', 24.99, 'Adaptador UGREEN USB-C a Ethernet para conexiones estables', 'ugreen_adapter.jpg', GETDATE()),
('Soporte de Teléfono para Auto', 'iOttie', 'Accesorios', 29.99, 'Soporte de teléfono iOttie para el auto, ajustable y seguro', 'iottie_auto.jpg', GETDATE()),
('Estación de Carga 4 en 1', 'Nomad', 'Accesorios', 79.99, 'Estación de carga Nomad 4 en 1 para múltiples dispositivos', 'nomad_charge.jpg', GETDATE()),
('Soporte para Tablet', 'Lamicall', 'Accesorios', 27.99, 'Soporte para tablet Lamicall, ideal para ver videos', 'lamicall_tablet.jpg', GETDATE()),
('Bucle T de Cable', 'UGREEN', 'Accesorios', 9.99, 'Cable en bucle T de UGREEN, ideal para conexiones rápidas', 'ugreen_bucle.jpg', GETDATE()),
('Memoria RAM 8GB DDR4', 'Corsair', 'Accesorios', 89.99, 'Módulo de memoria RAM 8GB DDR4 Corsair para sistemas de alto rendimiento', 'corsair_ram8.jpg', GETDATE()),
('Webcam HD 1080p', 'Logitech', 'Accesorios', 69.99, 'Webcam HD 1080p Logitech, ideal para videoconferencias', 'logitech_webcam.jpg', GETDATE()),
-- Productos adicionales - Periféricos
('Monitor LED 22"', 'Acer', 'Periféricos', 149.99, 'Monitor LED Acer de 22", ideal para oficinas y hogares', 'acer_monitor22.jpg', GETDATE()),
('Monitor Curvo 32"', 'Samsung', 'Periféricos', 499.99, 'Monitor curvo Samsung de 32" para una experiencia inmersiva', 'samsung_curvo32.jpg', GETDATE()),
('Cámara Web HD', 'Logitech', 'Periféricos', 89.99, 'Cámara web HD Logitech con micrófono integrado', 'logitech_webcam_hd.jpg', GETDATE()),
('Router Doble Banda AC1900', 'NETGEAR', 'Periféricos', 129.99, 'Router NETGEAR Doble Banda AC1900, ideal para streaming y gaming', 'netgear_ac1900.jpg', GETDATE()),
('Impresora Láser', 'Brother', 'Periféricos', 149.99, 'Impresora láser Brother, alta velocidad y rendimiento', 'brother_laser.jpg', GETDATE()),
('Altavoces 2.1 Sistema', 'Logitech', 'Periféricos', 79.99, 'Sistema de altavoces 2.1 Logitech para una experiencia de audio completa', 'logitech_2_1.jpg', GETDATE()),
('Sistema de Sonido Bluetooth', 'Bose', 'Periféricos', 199.99, 'Sistema de sonido Bluetooth Bose, con graves potentes y conectividad versátil', 'bose_sound.jpg', GETDATE()),
('Switch de Red 8 puertos', 'Cisco', 'Periféricos', 249.99, 'Switch de red Cisco de 8 puertos para redes empresariales', 'cisco_switch8.jpg', GETDATE()),
('Proyector HD', 'Epson', 'Periféricos', 399.99, 'Proyector HD Epson para presentaciones y entretenimiento', 'epson_proyector_hd.jpg', GETDATE()),
('Cámara de Seguridad IP', 'Hikvision', 'Periféricos', 89.99, 'Cámara de seguridad IP Hikvision con visión nocturna', 'hikvision_camara.jpg', GETDATE()),
('Escáner Multifunción', 'Brother', 'Periféricos', 119.99, 'Escáner multifunción Brother, ideal para oficinas pequeñas', 'brother_escanner.jpg', GETDATE()),
('Tableta Galaxy Tab S6', 'Samsung', 'Computadoras', 499.99, 'Tableta Samsung Galaxy Tab S6, pantalla de 10.5", 64GB de almacenamiento y batería de larga duración', 'samsung_galaxy_tab_s6.jpg', GETDATE()),
('Smartphone iPhone 13', 'Apple', 'Dispositivos Móviles', 899.99, 'Apple iPhone 13, 128GB, cámara dual y procesador A15 Bionic', 'iphone13.jpg', GETDATE()),
('Smartphone Galaxy S21', 'Samsung', 'Dispositivos Móviles', 799.99, 'Samsung Galaxy S21, 128GB, cámara triple y diseño elegante', 'galaxy_s21.jpg', GETDATE()),
('Smartwatch Series 6', 'Apple', 'Accesorios', 399.99, 'Apple Watch Series 6, monitor de salud, seguimiento de actividad y conectividad GPS', 'apple_watch_series6.jpg', GETDATE()),
('Smartwatch Galaxy Watch 4', 'Samsung', 'Accesorios', 299.99, 'Samsung Galaxy Watch 4, seguimiento de actividad y diseño moderno', 'galaxy_watch4.jpg', GETDATE()),
('Auriculares True Wireless', 'Apple', 'Accesorios', 199.99, 'Auriculares True Wireless de Apple con sonido de alta fidelidad', 'apple_true_wireless.jpg', GETDATE()),
('Teclado Inalámbrico Multi-dispositivo', 'Logitech', 'Accesorios', 69.99, 'Teclado inalámbrico Logitech con conectividad para múltiples dispositivos', 'logitech_wireless_keyboard.jpg', GETDATE()),
('Mouse Vertical', 'Anker', 'Accesorios', 49.99, 'Mouse vertical ergonómico Anker para reducir la fatiga al trabajar', 'anker_vertical_mouse.jpg', GETDATE()),
('Cargador Rápido USB-C', 'Samsung', 'Accesorios', 29.99, 'Cargador USB-C rápido de Samsung, compatible con dispositivos modernos', 'samsung_usb_c_charger.jpg', GETDATE()),
('Batería Portátil Solar', 'Anker', 'Accesorios', 89.99, 'Batería portátil con panel solar, ideal para viajes y emergencias', 'anker_solar_powerbank.jpg', GETDATE()),
('Disco Duro SSD 1TB', 'Samsung', 'Accesorios', 149.99, 'Disco SSD 1TB de Samsung con alta velocidad de lectura y escritura', 'samsung_ssd_1tb.jpg', GETDATE()),
('Memoria RAM 16GB DDR4', 'Kingston', 'Accesorios', 109.99, 'Módulo de memoria RAM de 16GB DDR4 Kingston para PCs de alto rendimiento', 'kingston_ram16.jpg', GETDATE()),
('Monitor UltraWide 34"', 'Dell', 'Periféricos', 499.99, 'Monitor UltraWide Dell de 34", ideal para productividad y entretenimiento', 'dell_ultrawide34.jpg', GETDATE()),
('Monitor LED 27"', 'HP', 'Periféricos', 299.99, 'Monitor LED HD de 27" de HP con excelente calidad de imagen', 'hp_monitor27.jpg', GETDATE()),
('Teclado y Mouse Inalámbricos Combo', 'Logitech', 'Accesorios', 89.99, 'Combo inalámbrico de teclado y mouse Logitech, perfecto para oficina', 'logitech_combo.jpg', GETDATE()),
('Estación de Trabajo Compacta', 'Dell', 'Computadoras', 1299.99, 'Estación de trabajo compacta Dell para profesionales, con alto rendimiento', 'dell_workstation.jpg', GETDATE()),
('Laptop Convertible 2 en 1', 'Lenovo', 'Computadoras', 999.99, 'Laptop convertible Lenovo 2 en 1 con pantalla táctil y batería de larga duración', 'lenovo_convertible.jpg', GETDATE()),
('Portátil Gamer ROG', 'Asus', 'Computadoras', 1499.99, 'Laptop gamer Asus ROG, ideal para juegos exigentes y altos gráficos', 'asus_rog.jpg', GETDATE()),
('Monitor Curvo 34 UltraWide', 'LG', 'Periféricos', 549.99, 'Monitor curvo ultra ancho LG de 34", excepcional para multitarea y entretenimiento', 'lg_ultrawide34.jpg', GETDATE()),
('Tablet Windows 10', 'Microsoft', 'Computadoras', 399.99, 'Tablet Microsoft con Windows 10, ideal para productividad y entretenimiento', 'microsoft_tablet.jpg', GETDATE()),
('Cámara Digital Compacta', 'Canon', 'Periféricos', 299.99, 'Cámara digital compacta Canon para fotografía casual y viajes', 'canon_compact_camera.jpg', GETDATE()),
('Micrófono USB Condensador', 'Blue', 'Accesorios', 129.99, 'Micrófono USB Blue Yeti, ideal para streaming y grabación de podcasts', 'blue_yeti.jpg', GETDATE()),
('Impresora 3D Desktop', 'Creality', 'Periféricos', 239.99, 'Impresora 3D de escritorio Creality para creación de prototipos y diseños', 'creality_3d_printer.jpg', GETDATE()),
('Escáner de Documentos Portátil', 'Fujitsu', 'Periféricos', 199.99, 'Escáner portátil Fujitsu para digitalizar documentos de forma rápida', 'fujitsu_scanner.jpg', GETDATE()),
('Router WiFi Mesh', 'Google', 'Periféricos', 199.99, 'Router WiFi Mesh de Google para cubrir grandes espacios con señal estable', 'google_mesh.jpg', GETDATE()),
('Sistema de Videoconferencia', 'Logitech', 'Periféricos', 249.99, 'Sistema de videoconferencia Logitech con cámara y micrófono integrados', 'logitech_videoconf.jpg', GETDATE()),
('Altavoz Inteligente', 'Amazon', 'Accesorios', 79.99, 'Altavoz inteligente Amazon Echo con asistente Alexa integrado', 'amazon_echo.jpg', GETDATE());